### ISSUE TITLE
Your assistance may help gniza.org segment exporter

### ISSUE THREAD

**Issue by nickdyson** [VeloViewer/VeloViewer-V3#2]
Hello - this is probably not the right forum, but I am leveraging github membership to see if you can assist with a useful app. 
Please see the issue I raised at https://github.com/BenniG82/edge-segments/issues/18, because http://gniza.org/segments/#/segment/ is currently unavailable: "Due to this [Strava API] change it is currently impossible to display leaderboards or to find timing-data" ???

... or maybe it's an opportunity to add this to your portfolio.  Not all Veloviewer subscribers are Starva premium subscribers.  The gniza tool is supposed to enable Strava segments to be downloaded to Garmin devices without premium membership.  There appears to be no other tool currently available to do this.

Thanks
775217

**Comment by VeloViewer** [comment]
It isn't something VeloViewer could do because as far as I can tell it violates the T's & C's of Strava's API usage in that you aren't allowed to replicate Strava Premium functionality.
I'm also affected by the changes to the Strava API so you can no longer access effort data streams for other athletes in a leaderboard (or even the details of people in the leaderboard). I believe this is in order to comply with GDPR and not making available any personally identifiable information for people who haven't explicitly agreed to it.

**Comment by nickdyson** [comment]
Fair point.  I'll drop it. Thanks for replying.
